//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicSheetManager.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("IRONOCR.NIKLAUSBURREN.IRO241225.6478.80119-B3EA881ED6-AOEKVM2UMK26RB6-WFJQ7HRA7NL" +
            "U-GLBNIUZMSVGW-ONVDYJCGEM3S-S5MEJNZLH2TT-MUODCE-LXFIWUBTRCOQUA-IRONOCR.DOTNET.LI" +
            "TE.SUB-W5GDZK.RENEW.SUPPORT.25.DEC.2025")]
        public string IronOcrLicenseKey {
            get {
                return ((string)(this["IronOcrLicenseKey"]));
            }
            set {
                this["IronOcrLicenseKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CollapsedInstrumentGroups {
            get {
                return ((string)(this["CollapsedInstrumentGroups"]));
            }
            set {
                this["CollapsedInstrumentGroups"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DockLayout {
            get {
                return ((string)(this["DockLayout"]));
            }
            set {
                this["DockLayout"] = value;
            }
        }
    }
}
